# All constants related towards tower defense game

SCREEN_RESOLUTION_WIDTH = 1200
SCREEN_RESOLUTION_HEIGHT = 800

MAXIMUM_SONG_LOOP_TIME = -1

DART_CAT_TOWER_TYPE = "Dart Cat"
DART_CAT_IMAGE = "Towers/tower_img/DartCatTower.jpg"
DART_CAT_COST = 250
DART_CAT_ATTACK_POWER = 1
DART_CAT_ATTACK_SPEED = 6
DART_CAT_SELL_PRICE = 125
DART_CAT_TOWER_RADIUS = 250
DART_CAT_DEFAULT_LEVEL = 0

MACHO_CAT_TOWER_TYPE = "Macho Cat"
MACHO_CAT_IMAGE = "Towers/tower_img/MachoCatTower.jpg"
MACHO_CAT_COST = 600
MACHO_CAT_ATTACK_POWER = 2
MACHO_CAT_ATTACK_SPEED = 8
MACHO_CAT_SELL_PRICE = 300
MACHO_CAT_TOWER_RADIUS = 125
MACHO_CAT_DEFAULT_LEVEL = 0

ENEMY_IMAGE = "enemy_image"
NUMBER_OF_ENEMIES = "number_of_enemies"
ENEMY_HEALTH = "enemy_health"
ENEMY_SPEED = "speed"
ENEMY_IMAGE_SIZE = "image_size"

NORMAL_DOG_IMAGE = "Enemy/enemy_img/normal_dog.jpg"
NORMAL_DOG_IMAGE_SIZE = 1
NORMAL_DOG_HEALTH = 6
NORMAL_DOG_SPEED = 2

FAST_DOG_IMAGE = "Enemy/enemy_img/fast_dog.jpg"
FAST_DOG_IMAGE_SIZE = 1
FAST_DOG_HEALTH = 4
FAST_DOG_SPEED = 4

STRONG_DOG_IMAGE = "Enemy/enemy_img/strong_dog.jpg"
STRONG_DOG_IMAGE_SIZE = 1
STRONG_DOG_HEALTH = 30
STRONG_DOG_SPEED = 1

ANGRY_DOG_IMAGE = "Enemy/enemy_img/angry_dog.jpg"
ANGRY_DOG_IMAGE_SIZE = 1
ANGRY_DOG_HEALTH = 80
ANGRY_DOG_SPEED = 3

GIANT_NORMAL_DOG_IMAGE = "Enemy/enemy_img/normal_dog.jpg"
GIANT_NORMAL_DOG_IMAGE_SIZE = 2
GIANT_NORMAL_DOG_HEALTH = 400
GIANT_NORMAL_DOG_SPEED = 1

GIANT_FAST_DOG_IMAGE = "Enemy/enemy_img/fast_dog.jpg"
GIANT_FAST_DOG_IMAGE_SIZE = 2
GIANT_FAST_DOG_HEALTH = 150
GIANT_FAST_DOG_SPEED = 4

GIANT_STRONG_DOG_IMAGE = "Enemy/enemy_img/strong_dog.jpg"
GIANT_STRONG_DOG_IMAGE_SIZE = 2
GIANT_STRONG_DOG_HEALTH = 2500
GIANT_STRONG_DOG_SPEED = 0.5

GIANT_ANGRY_DOG_IMAGE = "Enemy/enemy_img/angry_dog.jpg"
GIANT_ANGRY_DOG_IMAGE_SIZE = 2
GIANT_ANGRY_DOG_HEALTH = 500
GIANT_ANGRY_DOG_SPEED = 2

KING_DOG_IMAGE = "Enemy/enemy_img/king_dog.jpg"
KING_DOG_IMAGE_SIZE = 4
KING_DOG_HEALTH = 50000
KING_DOG_SPEED = 0.25

DEAD_END_MAP = "dead_end"
SUNNY_MEADOW_MAP = "sunny_meadow"

FINAL_ROUND = 31